name: Frontend
on:
  push:
    branches: [main]
    paths:
      - "ToDoApp.Frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "ToDoApp.Frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ToDoApp.Frontend
        run: npm ci

      - name: Build frontend
        working-directory: ToDoApp.Frontend
        run: npm run build

      - name: Test frontend
        working-directory: ToDoApp.Frontend
        run: npm test

      # - name: Build Docker image
      #   working-directory: ToDoApp.Frontend
      #   run: docker build -t todoapp-frontend:latest -f Dockerfile .
